// Data AI tools yang lengkap untuk Compare Section
const aiData = {
    // AI Utama/Populer
    chatgpt: {
        name: "ChatGPT",
        logo: "C",
        logoClass: "chatgpt-logo",
        category: "Text & Conversation",
        description: "Conversational AI that understands text, images, and code.",
        tags: ["Information", "Conversation", "Coding", "Education", "Multimodal", "Translation", "Ideation"],
        speed: "⚡ Very Fast",
        accuracy: "9.5/10",
        languages: "🌐 50+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$20/month",
        freePlan: "✅",
        strength: "Plugin ecosystem",
        weakness: "Expensive",
        link: "https://openai.com",
        isPopular: true,
        gradient: "linear-gradient(135deg, #10a37f, #1a7f64)",
        isTopModel: true
    },
    claude: {
        name: "Claude",
        logo: "A",
        logoClass: "claude-logo",
        category: "Text & Analysis",
        description: "Text reasoning AI with long context and deep analysis.",
        tags: ["Information", "Analysis", "Research", "Writing"],
        speed: "⚡ Fast",
        accuracy: "9.3/10",
        languages: "🌐 30+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$15/month",
        freePlan: "✅",
        strength: "Deep analysis",
        weakness: "No visual output",
        link: "https://claude.ai",
        isPopular: true,
        gradient: "linear-gradient(135deg, #f2a900, #d48e00)",
        isTopModel: true
    },
    gemini: {
        name: "Gemini",
        logo: "G",
        logoClass: "gemini-logo",
        category: "Multimodal",
        description: "Google's multimodal AI for research, conversation, and coding.",
        tags: ["Information", "Conversation", "Coding", "Research", "Multimodal"],
        speed: "⚡ Moderate",
        accuracy: "9.1/10",
        languages: "🌐 25+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$19/month",
        freePlan: "❌",
        strength: "Google tools integration",
        weakness: "Inconsistent speed",
        link: "https://gemini.google.com",
        isPopular: true,
        gradient: "linear-gradient(135deg, #4285f4, #34a853)",
        isTopModel: true
    },
    perplexity: {
        name: "Perplexity AI",
        logo: "P",
        logoClass: "perplexity-logo",
        category: "Research",
        description: "AI-powered search engine providing cited answers.",
        tags: ["Information", "Research", "Conversation"],
        speed: "⚡ Very Fast",
        accuracy: "9.4/10",
        languages: "🌐 20+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$20/month",
        freePlan: "✅",
        strength: "Accurate citations",
        weakness: "Limited creative tasks",
        link: "https://www.perplexity.ai",
        isPopular: true,
        gradient: "linear-gradient(135deg, #1e3a8a, #3b82f6)",
        isTopModel: false
    },
    midjourney: {
        name: "Midjourney",
        logo: "M",
        logoClass: "midjourney-logo",
        category: "Image Generation",
        description: "Generates high-quality artistic images from text prompts.",
        tags: ["Image", "Creative", "Art"],
        speed: "⚡ Fast",
        accuracy: "9.2/10",
        languages: "🌐 10+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$10/month",
        freePlan: "❌",
        strength: "Artistic quality",
        weakness: "Discord-only interface",
        link: "https://midjourney.com",
        isPopular: true,
        gradient: "linear-gradient(135deg, #1a1a2e, #16213e)",
        isTopModel: false
    },

    // 10 AI TERBARU
    deepseekr1: {
        name: "DeepSeek R1",
        logo: "D",
        logoClass: "deepseek-logo",
        category: "Reasoning & Research",
        description: "Advanced reasoning model optimized for complex problem solving and research tasks.",
        tags: ["Reasoning", "Research", "Analysis", "Coding"],
        speed: "⚡ Fast",
        accuracy: "9.3/10",
        languages: "🌐 40+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$12/month",
        freePlan: "✅",
        strength: "Advanced reasoning capabilities",
        weakness: "Limited multimodal",
        link: "https://deepseek.com",
        isPopular: true,
        gradient: "linear-gradient(135deg, #7e22ce, #a855f7)",
        isTopModel: true
    },
    perplexitysonic: {
        name: "Perplexity Sonic",
        logo: "P",
        logoClass: "perplexitysonic-logo",
        category: "Search & Research",
        description: "Ultra-fast search AI with real-time information and enhanced accuracy.",
        tags: ["Search", "Research", "Real-time", "Information"],
        speed: "⚡ Ultra Fast",
        accuracy: "9.6/10",
        languages: "🌐 30+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$25/month",
        freePlan: "✅",
        strength: "Real-time information",
        weakness: "Higher cost",
        link: "https://perplexity.ai",
        isPopular: true,
        gradient: "linear-gradient(135deg, #dc2626, #ef4444)",
        isTopModel: false
    },
    claude37: {
        name: "Claude 3.7",
        logo: "A",
        logoClass: "claude37-logo",
        category: "Text & Analysis",
        description: "Latest Claude model with enhanced reasoning and extended context window.",
        tags: ["Reasoning", "Analysis", "Writing", "Research"],
        speed: "⚡ Very Fast",
        accuracy: "9.7/10",
        languages: "🌐 35+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$18/month",
        freePlan: "✅",
        strength: "Extended context window",
        weakness: "No image generation",
        link: "https://claude.ai",
        isPopular: true,
        gradient: "linear-gradient(135deg, #d97706, #f59e0b)",
        isTopModel: true
    },
    geminiflash20: {
        name: "Gemini Flash 2.0",
        logo: "G",
        logoClass: "geminiflash-logo",
        category: "Multimodal",
        description: "Lightning-fast Gemini variant optimized for speed and efficiency.",
        tags: ["Speed", "Multimodal", "Efficiency", "Conversation"],
        speed: "⚡ Ultra Fast",
        accuracy: "9.0/10",
        languages: "🌐 20+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$15/month",
        freePlan: "❌",
        strength: "Extremely fast responses",
        weakness: "Lower accuracy than Pro",
        link: "https://gemini.google.com",
        isPopular: true,
        gradient: "linear-gradient(135deg, #3b82f6, #60a5fa)",
        isTopModel: false
    },

    // 10 AI BARU DENGAN GAMBAR/LOGO EMOJI
    openaiova: {
        name: "OpenAI O1",
        logo: "🚀",
        logoClass: "openaiova-logo",
        category: "Reasoning & Problem Solving",
        description: "OpenAI's reasoning-focused model for complex problem solving with advanced logical capabilities.",
        tags: ["Reasoning", "Problem Solving", "Analysis", "Research", "Advanced"],
        speed: "⚡ Moderate",
        accuracy: "9.8/10",
        languages: "🌐 50+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$30/month",
        freePlan: "❌",
        strength: "Superior reasoning capabilities",
        weakness: "Very expensive",
        link: "https://openai.com",
        isPopular: true,
        gradient: "linear-gradient(135deg, #059669, #10b981)",
        isTopModel: false
    },
    xaidark: {
        name: "xAI Dark",
        logo: "🌌",
        logoClass: "xaidark-logo",
        category: "Research & Analysis",
        description: "xAI's research-focused model with deep analytical capabilities and scientific approach.",
        tags: ["Research", "Analysis", "Science", "Mathematics", "Deep Learning"],
        speed: "⚡ Fast",
        accuracy: "9.4/10",
        languages: "🌐 25+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$22/month",
        freePlan: "✅",
        strength: "Scientific analysis and research",
        weakness: "Niche focus area",
        link: "https://x.ai",
        isPopular: false,
        gradient: "linear-gradient(135deg, #000000, #4b5563)",
        isTopModel: false
    },
    mistralnexus: {
        name: "Mistral Nexus",
        logo: "⚡",
        logoClass: "mistralnexus-logo",
        category: "Open Source",
        description: "Mistral's latest open-source model with enterprise features and community-driven development.",
        tags: ["Open Source", "Enterprise", "Coding", "Analysis", "Community"],
        speed: "⚡ Very Fast",
        accuracy: "9.2/10",
        languages: "🌐 20+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$8/month",
        freePlan: "✅",
        strength: "Open source flexibility and customization",
        weakness: "Smaller community support",
        link: "https://mistral.ai",
        isPopular: false,
        gradient: "linear-gradient(135deg, #7c3aed, #a78bfa)",
        isTopModel: false
    },
    coherecoral: {
        name: "Cohere Coral",
        logo: "🐠",
        logoClass: "coherecoral-logo",
        category: "Enterprise",
        description: "Cohere's enterprise model with enhanced RAG capabilities and business-focused features.",
        tags: ["Enterprise", "RAG", "Business", "Analysis", "Corporate"],
        speed: "⚡ Fast",
        accuracy: "9.1/10",
        languages: "🌐 15+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$20/month",
        freePlan: "❌",
        strength: "Enterprise RAG and business integration",
        weakness: "Limited language support",
        link: "https://cohere.com",
        isPopular: false,
        gradient: "linear-gradient(135deg, #ec4899, #f472b6)",
        isTopModel: false
    },
    anthropicsonnet: {
        name: "Anthropic Sonnet",
        logo: "🎵",
        logoClass: "anthropicsonnet-logo",
        category: "Text & Safety",
        description: "Anthropic's balanced model focusing on safety, ethics, and reliable performance.",
        tags: ["Safety", "Text", "Analysis", "Research", "Ethical AI"],
        speed: "⚡ Moderate",
        accuracy: "9.3/10",
        languages: "🌐 30+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$16/month",
        freePlan: "✅",
        strength: "Safety-focused and ethical outputs",
        weakness: "Conservative response style",
        link: "https://anthropic.com",
        isPopular: false,
        gradient: "linear-gradient(135deg, #f59e0b, #fbbf24)",
        isTopModel: false
    },
    metaquest: {
        name: "Meta Quest",
        logo: "🕶️",
        logoClass: "metaquest-logo",
        category: "Multimodal",
        description: "Meta's advanced multimodal model for diverse applications and social integrations.",
        tags: ["Multimodal", "Social", "Creative", "Analysis", "Integration"],
        speed: "⚡ Fast",
        accuracy: "9.0/10",
        languages: "🌐 40+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$14/month",
        freePlan: "✅",
        strength: "Multimodal capabilities and social integration",
        weakness: "Relatively new to market",
        link: "https://meta.ai",
        isPopular: false,
        gradient: "linear-gradient(135deg, #1877f2, #42b883)",
        isTopModel: false
    },
    stabilitymatrix: {
        name: "Stability Matrix",
        logo: "🎨",
        logoClass: "stabilitymatrix-logo",
        category: "Creative & Art",
        description: "Advanced creative AI for artistic generation, design, and multimedia content creation.",
        tags: ["Creative", "Art", "Design", "Multimedia", "Generation"],
        speed: "⚡ Fast",
        accuracy: "9.1/10",
        languages: "🌐 15+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$12/month",
        freePlan: "✅",
        strength: "Advanced creative and artistic capabilities",
        weakness: "Specialized use case",
        link: "https://stability.ai",
        isPopular: true,
        gradient: "linear-gradient(135deg, #8b5cf6, #c4b5fd)",
        isTopModel: false
    },
    neurallink: {
        name: "Neural Link",
        logo: "🧠",
        logoClass: "neurallink-logo",
        category: "Advanced AI",
        description: "Cutting-edge AI with neural network optimization for complex pattern recognition.",
        tags: ["Advanced", "Neural", "Patterns", "Research", "Innovation"],
        speed: "⚡ Very Fast",
        accuracy: "9.6/10",
        languages: "🌐 35+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$28/month",
        freePlan: "❌",
        strength: "Advanced neural network capabilities",
        weakness: "High computational requirements",
        link: "https://neuralink.com",
        isPopular: false,
        gradient: "linear-gradient(135deg, #dc2626, #f87171)",
        isTopModel: false
    },
    quantumai: {
        name: "Quantum AI",
        logo: "⚛️",
        logoClass: "quantumai-logo",
        category: "Quantum Computing",
        description: "Quantum-inspired AI for complex calculations and optimization problems.",
        tags: ["Quantum", "Calculation", "Optimization", "Advanced", "Science"],
        speed: "⚡ Ultra Fast",
        accuracy: "9.7/10",
        languages: "🌐 10+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$35/month",
        freePlan: "❌",
        strength: "Quantum computing optimization",
        weakness: "Limited general applications",
        link: "https://quantumai.com",
        isPopular: false,
        gradient: "linear-gradient(135deg, #06b6d4, #67e8f9)",
        isTopModel: false
    },
    deepmindomega: {
        name: "DeepMind Omega",
        logo: "🔬",
        logoClass: "deepmindomega-logo",
        category: "Research & Science",
        description: "DeepMind's research powerhouse for scientific discovery and complex problem solving.",
        tags: ["Research", "Science", "Discovery", "Analysis", "Advanced"],
        speed: "⚡ Fast",
        accuracy: "9.8/10",
        languages: "🌐 25+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$25/month",
        freePlan: "❌",
        strength: "Scientific research and discovery",
        weakness: "Academic focus",
        link: "https://deepmind.com",
        isPopular: false,
        gradient: "linear-gradient(135deg, #1d4ed8, #3b82f6)",
        isTopModel: false
    },

    // AI lainnya yang sudah ada sebelumnya
    runway: {
        name: "Runway ML",
        logo: "R",
        logoClass: "runway-logo",
        category: "Video & Multimedia",
        description: "AI platform for creating and editing videos automatically.",
        tags: ["Video", "Creative", "Editing"],
        speed: "⚡ Moderate",
        accuracy: "8.9/10",
        languages: "🌐 20+",
        imageGeneration: "✅",
        apiSupport: "✅",
        price: "$15/month",
        freePlan: "✅",
        strength: "Video generation",
        weakness: "Steep learning curve",
        link: "https://runwayml.com",
        isPopular: true,
        gradient: "linear-gradient(135deg, #000000, #333333)",
        isTopModel: false
    },
    elevenlabs: {
        name: "ElevenLabs",
        logo: "E",
        logoClass: "elevenlabs-logo",
        category: "Voice AI",
        description: "Realistic text-to-speech with expressive emotional tone.",
        tags: ["Voice", "Narration", "Audio"],
        speed: "⚡ Fast",
        accuracy: "9.0/10",
        languages: "🌐 29+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$5/month",
        freePlan: "✅",
        strength: "Human-like voices",
        weakness: "Limited free credits",
        link: "https://elevenlabs.io",
        isPopular: true,
        gradient: "linear-gradient(135deg, #000000, #1a1a1a)",
        isTopModel: false
    },
    githubcopilot: {
        name: "GitHub Copilot",
        logo: "G",
        logoClass: "githubcopilot-logo",
        category: "Coding",
        description: "Coding assistant that writes and explains code in real time.",
        tags: ["Coding", "Productivity", "Education"],
        speed: "⚡ Very Fast",
        accuracy: "9.3/10",
        languages: "🌐 15+",
        imageGeneration: "❌",
        apiSupport: "✅",
        price: "$10/month",
        freePlan: "❌",
        strength: "Code completion",
        weakness: "Limited to coding",
        link: "https://github.com/features/copilot",
        isPopular: true,
        gradient: "linear-gradient(135deg, #000000, #6e5494)",
        isTopModel: false
    }
};

// Data untuk Dashboard Comparison
const dashboardAIData = {
    chatgpt: {
        name: "ChatGPT",
        category: "Text & Conversation",
        intelligence: 95,
        speed: 90,
        cost: 30,
        color: "#10a37f",
        reasoning: 92,
        multimodal: true
    },
    deepseekr1: {
        name: "DeepSeek R1",
        category: "Reasoning & Research",
        intelligence: 94,
        speed: 88,
        cost: 12,
        color: "#7e22ce",
        reasoning: 96,
        multimodal: false
    },
    claude37: {
        name: "Claude 3.7",
        category: "Text & Analysis",
        intelligence: 96,
        speed: 85,
        cost: 18,
        color: "#d97706",
        reasoning: 95,
        multimodal: false
    },
    gemini: {
        name: "Gemini",
        category: "Multimodal",
        intelligence: 93,
        speed: 87,
        cost: 19,
        color: "#4285f4",
        reasoning: 90,
        multimodal: true
    },
    perplexity: {
        name: "Perplexity AI",
        category: "Research",
        intelligence: 91,
        speed: 92,
        cost: 20,
        color: "#1e3a8a",
        reasoning: 89,
        multimodal: false
    },
    
    // 10 AI BARU UNTUK DASHBOARD
    openaiova: {
        name: "OpenAI O1",
        category: "Reasoning & Problem Solving",
        intelligence: 97,
        speed: 82,
        cost: 30,
        color: "#059669",
        reasoning: 98,
        multimodal: false
    },
    xaidark: {
        name: "xAI Dark",
        category: "Research & Analysis",
        intelligence: 92,
        speed: 84,
        cost: 22,
        color: "#000000",
        reasoning: 93,
        multimodal: false
    },
    mistralnexus: {
        name: "Mistral Nexus",
        category: "Open Source",
        intelligence: 90,
        speed: 89,
        cost: 8,
        color: "#7c3aed",
        reasoning: 89,
        multimodal: false
    },
    coherecoral: {
        name: "Cohere Coral",
        category: "Enterprise",
        intelligence: 91,
        speed: 86,
        cost: 20,
        color: "#ec4899",
        reasoning: 90,
        multimodal: false
    },
    anthropicsonnet: {
        name: "Anthropic Sonnet",
        category: "Text & Safety",
        intelligence: 90,
        speed: 83,
        cost: 16,
        color: "#f59e0b",
        reasoning: 91,
        multimodal: false
    },
    metaquest: {
        name: "Meta Quest",
        category: "Multimodal",
        intelligence: 89,
        speed: 87,
        cost: 14,
        color: "#1877f2",
        reasoning: 87,
        multimodal: true
    },
    stabilitymatrix: {
        name: "Stability Matrix",
        category: "Creative & Art",
        intelligence: 88,
        speed: 85,
        cost: 12,
        color: "#8b5cf6",
        reasoning: 84,
        multimodal: true
    },
    neurallink: {
        name: "Neural Link",
        category: "Advanced AI",
        intelligence: 96,
        speed: 92,
        cost: 28,
        color: "#dc2626",
        reasoning: 95,
        multimodal: true
    },
    quantumai: {
        name: "Quantum AI",
        category: "Quantum Computing",
        intelligence: 98,
        speed: 95,
        cost: 35,
        color: "#06b6d4",
        reasoning: 97,
        multimodal: false
    },
    deepmindomega: {
        name: "DeepMind Omega",
        category: "Research & Science",
        intelligence: 97,
        speed: 88,
        cost: 25,
        color: "#1d4ed8",
        reasoning: 96,
        multimodal: false
    },

    // Research Models lainnya
    perplexitysonic: {
        name: "Perplexity Sonic",
        category: "Search & Research",
        intelligence: 93,
        speed: 97,
        cost: 25,
        color: "#dc2626",
        reasoning: 88,
        multimodal: false
    },
    geminiflash20: {
        name: "Gemini Flash 2.0",
        category: "Multimodal",
        intelligence: 89,
        speed: 95,
        cost: 15,
        color: "#3b82f6",
        reasoning: 86,
        multimodal: true
    },
    midjourney: {
        name: "Midjourney",
        category: "Image Generation",
        intelligence: 85,
        speed: 78,
        cost: 10,
        color: "#1a1a2e",
        reasoning: 75,
        multimodal: false
    },
    runway: {
        name: "Runway ML",
        category: "Video & Multimedia",
        intelligence: 83,
        speed: 72,
        cost: 15,
        color: "#000000",
        reasoning: 78,
        multimodal: true
    },
    elevenlabs: {
        name: "ElevenLabs",
        category: "Voice AI",
        intelligence: 80,
        speed: 88,
        cost: 5,
        color: "#000000",
        reasoning: 76,
        multimodal: false
    },
    githubcopilot: {
        name: "GitHub Copilot",
        category: "Coding",
        intelligence: 92,
        speed: 94,
        cost: 10,
        color: "#6e5494",
        reasoning: 89,
        multimodal: false
    }
};